export const VCPPalette = (mode) => ({
  mode,
  ...(mode === 'light'
    ? {
        primary: {
          main: '#5B75F2',
          light: '#A8B6FF',
          dark: '#3C51C9',
          contrastText: '#FFFFFF',
          hover: '#4F6DE6',
          active: '#3D53B6',
          disabled: '#C7D1FF',
        },
        secondary: {
          main: '#FFB74D',
          light: '#FFD180',
          dark: '#FB8C00',
          contrastText: '#000000',
          hover: '#FFA726',
          active: '#E68100',
          disabled: '#FFE0B2',
        },
        danger: {
          main: '#E54B4B',
          light: '#FF7D7D',
          dark: '#C62828',
          contrastText: '#FFFFFF',
          hover: '#D44141',
          active: '#A82020',
          disabled: '#F5C6C6',
        },
        warning: {
          main: '#F59E0B',
          light: '#FFC75A',
          dark: '#D08700',
          contrastText: '#000000',
          hover: '#E8A806',
          active: '#C27D00',
          disabled: '#FFE08A',
        },
        success: {
          main: '#22C55E',
          light: '#6EE7B7',
          dark: '#15803D',
          contrastText: '#FFFFFF',
          hover: '#16A34A',
          active: '#116530',
          disabled: '#BDF9D8',
        },
        info: {
          main: '#3DAEF4',
          light: '#81D4FA',
          dark: '#0288D1',
          contrastText: '#FFFFFF',
          hover: '#2196F3',
          active: '#0D68A9',
          disabled: '#B3E5FC',
        },
        background: {
          default: '#F3F7FF',
          paper: '#FFFFFF',
          contrast: '#E3E8F2',
          overlay: 'rgba(0, 0, 0, 0.05)',
        },
        text: {
          primary: '#2D3748',
          secondary: '#4A5568',
          disabled: '#A0AEC0',
          hint: '#718096',
          placeholder: '#CBD5E0',
        },
        border: {
          default: '#E2E8F0',
          hover: '#A0AEC0',
          active: '#718096',
        },
        table: {
          header: '#E8ECF5',
          body: '#FFFFFF',
        },
        button: {
          default: '#5B75F2',
          hover: '#4F6DE6',
          active: '#3C51C9',
          focus: '#A8B6FF',
          disabled: '#C7D1FF',
        },
      }
    : {
        primary: {
          main: '#4A5EBC',
          light: '#6E83E0',
          dark: '#364785',
          contrastText: '#FFFFFF',
          hover: '#5C73D6',
          active: '#3E529D',
          disabled: '#7A8BC9',
        },
        secondary: {
          main: '#FFB84E',
          light: '#FFD68A',
          dark: '#E69026',
          contrastText: '#1A1A1A',
          hover: '#FF9F33',
          active: '#C8781C',
          disabled: '#FFDCB5',
        },
        danger: {
          main: '#D45252',
          light: '#F57171',
          dark: '#B33333',
          contrastText: '#FFFFFF',
          hover: '#C64747',
          active: '#922929',
          disabled: '#E99C9C',
        },
        warning: {
          main: '#EAB308',
          light: '#FDE047',
          dark: '#B99105',
          contrastText: '#000000',
          hover: '#E0A006',
          active: '#9F7403',
          disabled: '#F9D776',
        },
        success: {
          main: '#21A665',
          light: '#5FD995',
          dark: '#166344',
          contrastText: '#FFFFFF',
          hover: '#1C8F56',
          active: '#125537',
          disabled: '#8FD5B0',
        },
        info: {
          main: '#2684C8',
          light: '#6FBDE8',
          dark: '#175A88',
          contrastText: '#FFFFFF',
          hover: '#2A95D4',
          active: '#1B6D9C',
          disabled: '#A3D8F5',
        },
        background: {
          default: '#232539',
          paper: '#1C1E33',
          contrast: '#2C2F48',
          overlay: 'rgba(255, 255, 255, 0.06)',
        },
        text: {
          primary: '#F3F7FF',
          secondary: '#CBD5E1',
          disabled: '#9CA3AF',
          hint: '#6B7280',
          placeholder: '#A0AEC0',
        },
        border: {
          default: '#3C3F56',
          hover: '#51557A',
          active: '#6B6D82',
        },
        table: {
          header: '#2C2F48',
          body: '#232539',
        },
        button: {
          default: '#4A5EBC',
          hover: '#5C73D6',
          active: '#364785',
          focus: '#6E83E0',
          disabled: '#7A8BC9',
        },
      }),
});
