export const VCPPalette = (mode) => ({
  mode,
  ...(mode === 'light'
    ? {
        primary: {
          main: '#001159',
          light: '#4D5DAA',
          dark: '#000A3A',
          contrastText: '#ffffff',
          hover: '#00238B',
          active: '#001159',
          disabled: '#B3B6C4',
        },
        secondary: {
          main: '#FFD700',
          light: '#FFF4A3',
          dark: '#CCAC00',
          contrastText: '#000000',
          hover: '#FFCE00',
          active: '#FFB800',
          disabled: '#FFE066',
        },
        danger: {
          main: '#FF3B30',
          light: '#FF7D74',
          dark: '#C10000',
          contrastText: '#ffffff',
          hover: '#E02020',
          active: '#9A0000',
          disabled: '#FF8A80',
        },
        warning: {
          main: '#FF9500',
          light: '#FFC15B',
          dark: '#C57000',
          contrastText: '#000000',
          hover: '#FFA726',
          active: '#FF6F00',
          disabled: '#FFDD8D',
        },
        info: {
          main: '#007AFF',
          light: '#6EC3FF',
          dark: '#004DBF',
          contrastText: '#ffffff',
          hover: '#0063D1',
          active: '#0052AA',
          disabled: '#81D4FA',
        },
        success: {
          main: '#34C759',
          light: '#8EE59A',
          dark: '#007F29',
          contrastText: '#ffffff',
          hover: '#28A745',
          active: '#1A6E2D',
          disabled: '#A5D6A7',
        },
        white: '#ffffff',
        black: '#000000',
        background: {
          default: '#FCFCFC',
          paper: '#FFFFFF',
          contrast: '#E0E0E0',
          overlay: 'rgba(0, 0, 0, 0.05)',
        },
        text: {
          primary: '#001159',
          secondary: '#4D5DAA',
          disabled: '#B3B6C4',
          hint: '#6C758F',
          placeholder: '#6C758F',
        },
        table: {
          header: '#F1F8E9',
          body: '#FAFAFA',
        },
        title: {
          main: '#001159',
          secondary: '#4D5DAA',
        },
        button: {
          default: '#001159',
          hover: '#00238B',
          active: '#000A3A',
          focus: '#4D5DAA',
          disabled: '#B3B6C4',
        },
        border: {
          // default: '#B3B6C4',
          default: '#E7E9EE',
          hover: '#6C758F',
          active: '#4D5DAA',
        },
      }
    : {
        primary: {
          main: '#4D5DAA',
          light: '#6E8CF4',
          dark: '#001159',
          contrastText: '#ffffff',
          hover: '#3A4D8C',
          active: '#001159',
          disabled: '#5C6A9E',
        },
        secondary: {
          main: '#FFD700',
          light: '#FFE066',
          dark: '#CCAC00',
          contrastText: '#000000',
          hover: '#E0C000',
          active: '#CCAC00',
          disabled: '#FFF4A3',
        },
        danger: {
          main: '#FF3B30',
          light: '#FF7D74',
          dark: '#C10000',
          contrastText: '#ffffff',
          hover: '#E02020',
          active: '#9A0000',
          disabled: '#FF8A80',
        },
        warning: {
          main: '#FF9500',
          light: '#FFC15B',
          dark: '#C57000',
          contrastText: '#000000',
          hover: '#FFA726',
          active: '#FF6F00',
          disabled: '#FFDD8D',
        },
        info: {
          main: '#4D8EFF',
          light: '#81D4FA',
          dark: '#001159',
          contrastText: '#ffffff',
          hover: '#336ECC',
          active: '#00248F',
          disabled: '#6EC3FF',
        },
        success: {
          main: '#34C759',
          light: '#8EE59A',
          dark: '#007F29',
          contrastText: '#ffffff',
          hover: '#28A745',
          active: '#1A6E2D',
          disabled: '#A5D6A7',
        },
        white: '#ffffff',
        black: '#000000',
        background: {
          default: '#05070A',
          // default: '#121212',
          paper: '#1D1D1D',
          contrast: '#2A2A2A',
          overlay: 'rgba(255, 255, 255, 0.05)',
        },
        text: {
          primary: '#ffffff',
          secondary: '#B0BEC5',
          disabled: '#78909C',
          hint: '#90A4AE',
          placeholder: '#90A4AE',
        },
        table: {
          header: '#263238',
          body: '#37474F',
        },
        title: {
          main: '#BBDEFB',
          secondary: '#90CAF9',
        },
        button: {
          default: '#4D5DAA',
          hover: '#3A4D8C',
          active: '#001159',
          focus: '#6E8CF4',
          disabled: '#5C6A9E',
        },
        border: {
          default: '#20242A',
          // default: '#4D5DAA',
          hover: '#6C758F',
          active: '#90CAF9',
        },
      }),
});
