export const VCPPalette = (mode) => ({
  mode,
  ...(mode === 'light'
    ? {
        primary: {
          main: '#001159',
          light: '#4D5DAA',
          dark: '#000A3A',
          contrastText: '#FFFFFF',
          hover: '#00238B',
          active: '#000A3A',
          disabled: '#B3C7FF',
        },
        secondary: {
          main: '#FFD700',
          light: '#FFE066',
          dark: '#CCAC00',
          contrastText: '#000000',
          hover: '#E6B800',
          active: '#B38F00',
          disabled: '#FFE6A3',
        },
        danger: {
          main: '#FF3B30',
          light: '#FF7D74',
          dark: '#C10000',
          contrastText: '#FFFFFF',
          hover: '#E63946',
          active: '#A71D2A',
          disabled: '#FFB5BA',
        },
        warning: {
          main: '#FFA500',
          light: '#FFD580',
          dark: '#CC7A00',
          contrastText: '#000000',
          hover: '#E69500',
          active: '#B36600',
          disabled: '#FFE0B3',
        },
        success: {
          main: '#34C759',
          light: '#8EE59A',
          dark: '#007F29',
          contrastText: '#FFFFFF',
          hover: '#28A745',
          active: '#1A6E2D',
          disabled: '#A5D6A7',
        },
        info: {
          main: '#007AFF',
          light: '#6EC3FF',
          dark: '#004DBF',
          contrastText: '#FFFFFF',
          hover: '#1E88E5',
          active: '#01579B',
          disabled: '#B3E5FC',
        },
        background: {
          default: '#F4F6F8',
          paper: '#FFFFFF',
          contrast: '#E8EAED',
          overlay: 'rgba(0, 0, 0, 0.05)',
        },
        text: {
          primary: '#1F2937',
          secondary: '#4B5563',
          disabled: '#9CA3AF',
          hint: '#6B7280',
          placeholder: '#9CA3AF',
        },
        border: {
          default: '#E5E7EB',
          hover: '#9CA3AF',
          active: '#6B7280',
        },
        table: {
          header: '#F9FAFB',
          body: '#FFFFFF',
        },
        button: {
          default: '#001159',
          hover: '#00238B',
          active: '#000A3A',
          focus: '#4D5DAA',
          disabled: '#B3C7FF',
        },
      }
    : {
        primary: {
          main: '#001159',
          light: '#4D5DAA',
          dark: '#000A3A',
          contrastText: '#FFFFFF',
          hover: '#00238B',
          active: '#000A3A',
          disabled: '#5C6A9E',
        },
        secondary: {
          main: '#FFD700',
          light: '#FFE066',
          dark: '#CCAC00',
          contrastText: '#000000',
          hover: '#E6B800',
          active: '#B38F00',
          disabled: '#FFE0A6',
        },
        danger: {
          main: '#FF3B30',
          light: '#FF7D74',
          dark: '#C10000',
          contrastText: '#FFFFFF',
          hover: '#E63946',
          active: '#A71D2A',
          disabled: '#FFD3CF',
        },
        warning: {
          main: '#FFA500',
          light: '#FFD580',
          dark: '#CC7A00',
          contrastText: '#000000',
          hover: '#E69500',
          active: '#B36600',
          disabled: '#FFE0B3',
        },
        success: {
          main: '#34C759',
          light: '#8EE59A',
          dark: '#007F29',
          contrastText: '#FFFFFF',
          hover: '#28A745',
          active: '#1A6E2D',
          disabled: '#A5D6A7',
        },
        info: {
          main: '#007AFF',
          light: '#6EC3FF',
          dark: '#004DBF',
          contrastText: '#FFFFFF',
          hover: '#1E88E5',
          active: '#01579B',
          disabled: '#B3E5FC',
        },
        background: {
          default: '#121212',
          paper: '#1D1D1D',
          contrast: '#2A2A2A',
          overlay: 'rgba(255, 255, 255, 0.1)',
        },
        text: {
          primary: '#FFFFFF',
          secondary: '#D1D5DB',
          disabled: '#9CA3AF',
          hint: '#6B7280',
          placeholder: '#9CA3AF',
        },
        border: {
          default: '#374151',
          hover: '#9CA3AF',
          active: '#6B7280',
        },
        table: {
          header: '#1F2937',
          body: '#121212',
        },
        button: {
          default: '#001159',
          hover: '#00238B',
          active: '#000A3A',
          focus: '#4D5DAA',
          disabled: '#5C6A9E',
        },
      }),
});
